/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package youngfriend.gui;

import youngfriend.common.util.StringUtils;
import youngfriend.utils.PubUtil;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author xiong
 */
public class InputDlg extends javax.swing.JDialog {
    private boolean ok = false;

    public boolean validateData(String txt) {
        return true;
    }

    public boolean isOk() {
        return ok;
    }

    /**
     * Creates new form InputDlg
     */
    public InputDlg(java.awt.Window parent, String title, String value) {
        super(parent, ModalityType.APPLICATION_MODAL);
        setLocationRelativeTo(parent);
        initComponents();
        PubUtil.registerDlgBtn(this, ok_btn, cancel_btn, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                ok = false;
                dispose();
            }
        });
        ok_btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                onOk();

            }
        });
        this.getRootPane().setDefaultButton(ok_btn);
        if (!StringUtils.nullOrBlank(title)) {
            this.setTitle(title);
        }
        this.jTextField1.setText(value);
        this.setSize(265, 120);
        this.setPreferredSize(this.getSize());
        this.setVisible(true);
    }

    public void setValue(String value) {
        jTextField1.setText(value);
    }

    public String getTxt() {
        return this.jTextField1.getText().trim();
    }

    private void onOk() {
        if (!validateData(getTxt())) {
            return;
        }
        ok = true;
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ok_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        ok_btn.setText("确定");
        jPanel1.add(ok_btn);

        cancel_btn.setText("取消");
        jPanel1.add(cancel_btn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("输入:");
        jPanel2.add(jLabel1, java.awt.BorderLayout.LINE_START);
        jPanel2.add(jTextField1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton ok_btn;
    // End of variables declaration//GEN-END:variables
}
