/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package youngfriend.gui;

import youngfriend.bean.BeanDto;
import youngfriend.common.util.StringUtils;
import youngfriend.utils.PubUtil;

import javax.swing.DefaultListModel;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Collection;

/**
 * @author xiong
 */
public class ListDlg extends javax.swing.JDialog {
    private final DefaultListModel model;
    private boolean ok = false;

    public boolean isOk() {
        return ok;
    }

    /**
     * Creates new form ListDlg
     */
    public ListDlg(Window parent) {
        super(parent, ModalityType.APPLICATION_MODAL);
        model = new DefaultListModel();
        initComponents();
        PubUtil.registerDlgBtn(this, jButton1, jButton2, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                ok = false;
                dispose();
            }
        });
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                onOk();
            }
        });
        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                ok = true;
                jList1.clearSelection();
                dispose();
            }
        });
        jList1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                if (mouseEvent.getClickCount() < 2) {
                    return;
                }
                onOk();
            }
        });
    }

    private void onOk() {
        ok = true;
        dispose();
    }

    public void clear() {
        model.clear();
    }

    public void addItem(BeanDto fielddto) {
        model.addElement(fielddto);
    }

    public void addItems(Collection<BeanDto> items) {
        for (BeanDto dto : items) {
            addItem(dto);
        }

    }

    public void showDlg() {
        this.setLocationRelativeTo(this.getParent());
        ok = false;
        setVisible(true);
    }

    public BeanDto getSelect() {
        return (BeanDto) jList1.getSelectedValue();
    }

    public void setSelect(String key, String value) {
        jList1.clearSelection();
        if (StringUtils.nullOrBlank(value)) {
            return;
        }
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        int size = model.getSize();
        if (size < 1) {
            return;
        }
        for (int i = 0; i < size; i++) {
            BeanDto elementAt = (BeanDto) model.getElementAt(i);
            if (elementAt.getValue(key).equals(value)) {
                jList1.setSelectedValue(elementAt, true);
                return;
            }
        }
    }

    public void setSelect(BeanDto dto) {
        jList1.clearSelection();
        jList1.setSelectedValue(dto, true);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(260, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("确定");
        jPanel1.add(jButton1);

        jButton2.setText("取消");
        jPanel1.add(jButton2);

        jButton3.setText("清空");
        jPanel1.add(jButton3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jList1.setModel(model);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
