/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package youngfriend.gui;

import com.google.common.base.Strings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import youngfriend.utils.PubUtil;
import youngfriend.utils.ServiceInvoker;

import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 * @author xiong
 */
public class LoginDlg extends javax.swing.JDialog {
    private static final Logger logger = LoggerFactory.getLogger(LoginDlg.class);
    private int errLoginNum = 0;
    private boolean ok = false;


    /**
     * Creates new form LoginDlg
     */
    public LoginDlg(Window parent) {
        super(parent, ModalityType.APPLICATION_MODAL);
        initComponents();
        init();
    }

    private void init() {
        url_tf.setText(PubUtil.serviceConfig.getPro("url"));
        username_tf.setText(PubUtil.serviceConfig.getPro("username"));

        webproxy_cb.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent itemEvent) {
                if (ItemEvent.DESELECTED == itemEvent.getStateChange()) {
                    PubUtil.setWebProxy("", "");
                }
            }
        });
        setLocationRelativeTo(null);
        PubUtil.registerDlgBtn(this, jButton1, jButton2, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                dispose();
            }
        });
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        username_tf = new javax.swing.JTextField();
        url_tf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        password_tf = new javax.swing.JPasswordField();
        webproxy_cb = new javax.swing.JCheckBox();
        webparam_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("登陆");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("登录");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("取消");
        jPanel1.add(jButton2);

        webproxy_cb.setText("使用web代理服务");

        webparam_btn.setText("网路设置");
        webparam_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webparam_btnActionPerformed(evt);
            }
        });

        jLabel4.setText("用户名");

        jLabel5.setText("登录密码");

        jLabel6.setText("服务地址");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(username_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                                        .addComponent(password_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                                        .addComponent(url_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addComponent(webproxy_cb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(webparam_btn)))
                                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(username_tf)
                                        .addComponent(jLabel4))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(password_tf)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(url_tf)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(webproxy_cb)
                                        .addComponent(webparam_btn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login();
    }//GEN-LAST:event_jButton1ActionPerformed


    private void webparam_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webparam_btnActionPerformed
        setWebProxy();
    }//GEN-LAST:event_webparam_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password_tf;
    private javax.swing.JTextField url_tf;
    private javax.swing.JTextField username_tf;
    private javax.swing.JButton webparam_btn;
    private javax.swing.JCheckBox webproxy_cb;
    // End of variables declaration//GEN-END:variables

    private void login() {
        //校验
        String usernameVal = username_tf.getText();
        String passwordVal = new String(password_tf.getPassword());
        String serverurlVal = url_tf.getText();
        if (Strings.isNullOrEmpty(usernameVal)) {//用户名为空
            PubUtil.showMsg(this, "用户名不能为空！");
            username_tf.grabFocus();
            return;
        }
        if (Strings.isNullOrEmpty(serverurlVal)) {//服务命为空
            PubUtil.showMsg(this, "服务器地址不能为空！");
            url_tf.grabFocus();
            return;
        }
        try {
            ServiceInvoker.login(serverurlVal, usernameVal, passwordVal, webproxy_cb.isSelected());
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            errLoginNum++;//累加失败次数
            if (errLoginNum > 2) {//登录3次失败退出系统
                PubUtil.showMsg(this, e.getMessage() + "\n系统将自动关闭！");
                System.exit(0);
            }
            PubUtil.showMsg(this, e.getMessage());
            return;
        }
        ok = true;
        PubUtil.serviceConfig.addConfig("url", serverurlVal);
        PubUtil.serviceConfig.addConfig("username", usernameVal);
        PubUtil.serviceConfig.writeConfig();
        dispose();
    }

    private void setWebProxy() {
        new WebProxyDlg(this).setVisible(true);
    }

    public boolean isOk() {
        return ok;
    }
}
